package views;

import java.awt.Point;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import controller.Assignment4;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

/**
 *
 * @author Ilham A
 */
public class assignment4 extends javax.swing.JFrame {
    private Assignment4 controller;
    /**
     * Creates new form assignment3
     */
    public assignment4() {
        initComponents();
        controller = new Assignment4(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadFile = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnRead = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuButton = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        classTypeMenu = new javax.swing.JMenuItem();
        DNSValidMenu = new javax.swing.JMenuItem();
        rectArea = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Praktikum 4");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnRead.setText("Read File");

        btnSave.setText("Save File");

        menuBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuBar.setToolTipText("");

        menuButton.setText("Practice");
        menuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem1.setText("Read File");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuButton.add(jMenuItem1);

        classTypeMenu.setText("Save Byte File");
        classTypeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classTypeMenuActionPerformed(evt);
            }
        });
        menuButton.add(classTypeMenu);

        DNSValidMenu.setText("Filter Stream");
        DNSValidMenu.setEnabled(false);
        DNSValidMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNSValidMenuActionPerformed(evt);
            }
        });
        menuButton.add(DNSValidMenu);

        rectArea.setText("AreaCalculator");
        rectArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectAreaActionPerformed(evt);
            }
        });
        menuButton.add(rectArea);

        menuBar.add(menuButton);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnRead)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRead)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnRead() {
        return btnRead;
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public JFileChooser getLoadFile() {
        return loadFile;
    }

    public JTextArea getTxtArea() {
        return txtArea;
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        assignment1 menu;
        menu = new assignment1();
        menu.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void classTypeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classTypeMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        assignment2 menu;
        menu = new assignment2();
        menu.setVisible(true);
    }//GEN-LAST:event_classTypeMenuActionPerformed

    private void DNSValidMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNSValidMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        assignment4 menu = new assignment4();
        menu.setVisible(true);
    }//GEN-LAST:event_DNSValidMenuActionPerformed

    private void rectAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectAreaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AreaCalc rect = new AreaCalc();
        rect.setVisible(true);
    }//GEN-LAST:event_rectAreaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DNSValidMenu;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnSave;
    private javax.swing.JMenuItem classTypeMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFileChooser loadFile;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuButton;
    private javax.swing.JMenuItem rectArea;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables

    public Object getTxtPane() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
